var names =
  ["Acamar"
    , "Acrux"
    , "Adara"
    , "Adhil"
    , "Agena"
    , "Ain"
    , "Alcor"
    , "Aldebaran"
    , "Alfirk"
    , "Algenib"
    , "Algol"
    , "Algorab"
    , "Alkaid"
    , "Alkes"
    , "Almaak"
    , "Alnair"
    , "Alnath"
    , "Alnilam"
    , "Alnitak"
    , "Alniyat"
    , "Alphard"
    , "Alphekka"
    , "Alpheratz"
    , "Alrai"
    , "Alrisha"
    , "Alsafi"
    , "Alshain"
    , "Alshat"
    , "Alsuhail"
    , "Altair"
    , "Altarf"
    , "Alterf"
    , "Aludra"
    , "Alya"
    , "Alzirr"
    , "Ancha"
    , "Angetenar"
    , "Ankaa"
    , "Anser"
    , "Antares"
    , "Arcturus"
    , "Arneb"
    , "Arrakis"
    , "Ascella"
    , "Asterope"
    , "Atik"
    , "Atlas"
    , "Auva"
    , "Avior"
    , "Azha"
    , "Baham"
    , "Becrux"
    , "Beid"
    , "Bellatrix"
    , "Betelgeuse"
    , "Botein"
    , "Brachium"
    , "Canopus"
    , "Capella"
    , "Caph"
    , "Castor"
    , "Chara"
    , "Chort"
    , "Cursa"
    , "Dabih"
    , "Deneb"
    , "Denebola"
    , "Dheneb"
    , "Diadem"
    , "Diphda"
    , "Dschubba"
    , "Dsiban"
    , "Dubhe"
    , "Electra"
    , "Elnath"
    , "Enif"
    , "Etamin"
    , "Fomalhaut"
    , "Fornacis"
    , "Furud"
    , "Gacrux"
    , "Gianfar"
    , "Gomeisa"
    , "Grafias"
    , "Grumium"
    , "Hadar"
    , "Haedi"
    , "Hamal"
    , "Hassaleh"
    , "Heze"
    , "Homam"
    , "Izar"
    , "Jabbah"
    , "Kajam"
    , "Keid"
    , "Kitalpha"
    , "Kocab"
    , "Kraz"
    , "Kuma"
    , "Lesath"
    , "Maasym"
    , "Maia"
    , "Marfak"
    , "Marfic"
    , "Marfik"
    , "Markab"
    , "Matar"
    , "Mebsuta"
    , "Megrez"
    , "Meissa"
    , "Mekbuda"
    , "Menkar"
    , "Menkar"
    , "Menkent"
    , "Menkib"
    , "Merak"
    , "Merga"
    , "Merope"
    , "Mesarthim"
    , "Metallah"
    , "Minkar"
    , "Mintaka"
    , "Mira"
    , "Mirach"
    , "Miram"
    , "Mirphak"
    , "Mizar"
    , "Mufrid"
    , "Muliphen"
    , "Murzim"
    , "Muscida"
    , "Naos"
    , "Nash"
    , "Nashira"
    , "Nekkar"
    , "Nihal"
    , "Nunki"
    , "Nusakan"
    , "Peacock"
    , "Phad"
    , "Phaet"
    , "Pherkad"
    , "Pleione"
    , "Polaris"
    , "Pollux"
    , "Porrima"
    , "Prima"
    , "Procyon"
    , "Propus"
    , "Rana"
    , "Rastaban"
    , "Regulus"
    , "Rigel"
    , "Rotanev"
    , "Ruchba"
    , "Ruchbah"
    , "Rukbat"
    , "Sabik"
    , "Sadr"
    , "Saiph"
    , "Salm"
    , "Sargas"
    , "Sarin"
    , "Sceptrum"
    , "Secunda"
    , "Segin"
    , "Seginus"
    , "Sham"
    , "Sharatan"
    , "Shaula"
    , "Shedir"
    , "Sheliak"
    , "Sirius"
    , "Situla"
    , "Skat"
    , "Spica"
    , "Subra"
    , "Sulafat"
    , "Syrma"
    , "Talitha"
    , "Tarazed"
    , "Taygeta"
    , "Tegmen"
    , "Terebellum"
    , "Thabit"
    , "Theemim"
    , "Thuban"
    , "Turais"
    , "Tyl"
    , "Vega"
    , "Wasat"
    , "Wezen"
    , "Wezn"
    , "Yildun"
    , "Zaniah"
    , "Zaurak"
    , "Zavijah"
    , "Zibal"
    , "Zosma"
    , "Zuben"
];

var customnames = {
  random : function () {
    var count = names.length;
    var index = Math.floor(Math.random() * count);
    var result = names[index];

    // console.log('count / index / result');
    // console.log(count);
    // console.log(index);
    // console.log(result);

    return result;
  },
  count: function() {
    return names.length;
  },
  push: function(name) {
    names.push(name);
  }
}

// handle command line args, eg test
process.argv.forEach(function (val, index, array) {
  //console.log(index + ': ' + val);
  if (index == 2) {
    // run test
    var name = customnames.random();
    console.log(name);
  }
});

module.exports = customnames;
